# config.yaml
# Configuration file for the ML project

data:
  path: "data/raw/dataset.csv"
  
model:
  type: "RandomForest"
  parameters:
    n_estimators: 100
    max_depth: 10

training:
  test_size: 0.2
  random_state: 42
